name: custom_lint_builder
version: 0.3.3
description: A package to help writing custom linters
repository: https://github.com/invertase/dart_custom_lint

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  analyzer: ^5.7.0
  analyzer_plugin: ^0.11.0
  collection: ^1.16.0
  # Using tight constraints as custom_lint_builder communicate with each-other
  # using a specific contract
  custom_lint: 0.3.3
  # Using tight constraints as custom_lint_builder communicate with each-other
  # using a specific contract
  custom_lint_core: 0.3.3
  glob: ^2.1.1
  hotreloader: ^3.0.5
  meta: ^1.7.0
  path: ^1.8.0
  pubspec_parse: ^1.2.0
  rxdart: ^0.27.7

dev_dependencies:
  test: ^1.22.2
