name: lint_visitor_generator
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^8.0.0
  build: ^3.0.0
  build_config: ^1.1.0
  collection: ^1.17.1
  meta: ^1.7.0
  source_gen: ^4.0.0

dev_dependencies:
  build_runner: ^2.5.0
  build_test: ^3.0.0
  source_gen_test: ^1.0.4
