name: custom_lint_builder_example_lint
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

dependencies:
  analyzer: ^7.5.0
  analyzer_plugin: ^0.13.0
  custom_lint_builder:
    path: ../../../custom_lint_builder
