name: custom_lint_core
version: 0.7.1
description: A package to help writing custom linters
repository: https://github.com/invertase/dart_custom_lint

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^7.0.0
  analyzer_plugin: ^0.12.0
  collection: ^1.16.0
  custom_lint_visitor: ^1.0.0
  glob: ^2.1.2
  matcher: ^0.12.0
  meta: ^1.7.0
  package_config: ^2.1.0
  path: ^1.8.0
  pubspec_parse: ^1.2.2
  source_span: ^1.8.0
  uuid: ^4.5.1
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.3.3
  lint_visitor_generator:
    path: ../lint_visitor_generator
  test: ^1.22.2
