name: custom_lint_visitor
version: 1.0.0+7.7.0
description: A package that exports visitors for CustomLint.
repository: https://github.com/invertase/dart_custom_lint

environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

dependencies:
  analyzer: ">=7.4.5 <7.7.0"

dev_dependencies:
  build_runner: ^2.5.0
  lint_visitor_generator:
  test: ^1.22.2
