name: custom_lint_example_lint
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^7.0.0
  analyzer_plugin: ^0.13.0
  custom_lint_builder:
    path: ../../../custom_lint_builder

dev_dependencies:
  custom_lint:
