name: custom_lint_example_app
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  riverpod: ^2.0.0

dev_dependencies:
  custom_lint:
  custom_lint_example_lint:
    path: ./example_lint
