name: custom_lint
version: 0.0.9+1
description: Lint rules are a powerful way to improve the maintainability of a project. Custom Lint allows package authors and developers to easily write custom lint rules.
repository: https://github.com/invertase/dart_custom_lint

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  analyzer: ^4.7.0
  analyzer_plugin: ^0.10.0
  async: ^2.9.0
  cli_util: ^0.3.5
  collection: ^1.16.0
  meta: ^1.8.0
  package_config: ^2.1.0
  path: ^1.8.2
  pub_semver: ^2.1.1
  pubspec_parse: ^1.2.1
  recase: ^4.0.0
  riverpod: ^2.0.0-dev.9
  uuid: ^3.0.6
  yaml: ^3.1.1

dev_dependencies:
  test: ^1.21.5

executables:
  custom_lint: custom_lint
